apiVersion: v1
kind: Template
metadata:  
  name: rproxy-nginx
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rproxy-cache
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      run: rproxy-nginx
    name: rproxy-nginx
  spec:
    replicas: 1
    selector:
      run: rproxy-nginx
    strategy:
      resources:
        requests:
          cpu: 20m
          memory: 20Mi
        limits:
          cpu: 200m
          memory: 200Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          run: rproxy-nginx
      spec:
        containers:
        - image: registry.centos.org/kbsingh/openshift-nginx:latest
          imagePullPolicy: Always
          name: rproxy-nginx
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf 
            name: configmap-volume
          - mountPath: /var/cache/nginx
            name: volume-nginx-cache
        volumes:
        - name: configmap-volume
          configMap:
            name: rproxy-nginx
        - name: volume-nginx-cache
          persistentVolumeClaim:
            claimName: rproxy-cache
        dxnsPolics: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: rproxy-nginx
    annotations:
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: rproxy-nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata: 
    name: rproxy-nginx
  spec:
    to:
      kind: Service
      name: rproxy-nginx
      weight: 100
    wildcardPolicy: None
  status: {}
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: rproxy-nginx
  data:
    nginx.conf: |-
        worker_processes 1;
        error_log /dev/stdout info;
        pid /run/nginx.pid;
        daemon off;

        include /usr/share/nginx/modules/*.conf;

        events {
            worker_connections 1024;
        }

        http {
            log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

            access_log 		/dev/stdout main;
            client_body_temp_path /tmp;
            fastcgi_temp_path /tmp;
            scgi_temp_path /tmp;
            proxy_temp_path /tmp;
            uwsgi_temp_path /tmp;
            sendfile            on;
            tcp_nopush          on;
            tcp_nodelay         on;
            keepalive_timeout   65;
            types_hash_max_size 2048;

            include             /etc/nginx/mime.types;
            default_type        application/octet-stream;

            include /etc/nginx/conf.d/*.conf;

                upstream site {
                server bergene.biz:80; 
                }	

        #proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=nginx_cache:10m max_size=3g inactive=120m use_temp_path=off;

        server {
           listen 8080 default_server;
           server_name example.com;

                location / {
                proxy_pass http://site;
                proxy_set_header Connection "";
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Frame-Options SAMEORIGIN;	
                proxy_set_header Host bergene.biz; 
                proxy_buffers 256 16k;
                proxy_buffer_size 16k;
                proxy_read_timeout 600s;
                #proxy_cache nginx_cache;
                #proxy_cache_revalidate on;
                #proxy_cache_min_uses 2;
                #proxy_cache_use_stale timeout;
                #proxy_cache_lock on;
                }

            }
        }
